### ISSUE TITLE
AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by wikazp** [hazimhanif/svd_exp1#3]
Getting an attribute error for the function 'history'. Model.fit section producing the error

![image](https://user-images.githubusercontent.com/43385819/143341406-4ed98b3b-5d57-4349-8a08-0e4fdb9e162d.png)

**Comment by hazimfrodo** [comment]
The problem is related to the class weights argument in the `model.fit()` function.  
Apparently, after Tensorflow 2.1.0, they changed the way it behaves.  
You will not encounter this problem if you use **Tensorflow 2.0.0** as stated.  

A possible solution might be to follow the structure of the new Tensorflow.  
First, give a name for each output layer (out1, out2.....)   
Example:
```
output1 = tf.keras.layers.Dense(2, activation='softmax', name='out1')(mid_layers)
output2 = tf.keras.layers.Dense(2, activation='softmax', name='out2')(mid_layers)
```

Next, change the class_weights variable value to something like this:  
```
class_weights ={'out1': [1, 5.0], 'out2': [1, 5.0], ................<AND SO ON>................ }
```

If it didn't work. Try exploring other solutions from this post:   
https://datascience.stackexchange.com/questions/41698/how-to-apply-class-weight-to-a-multi-output-model
